# Generated by Django 4.0.6 on 2022-07-05 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Task name')),
                ('details', models.TextField()),
                ('fee', models.FloatField(default=0.0, verbose_name='Salary')),
                ('completed', models.BooleanField(default=False)),
                ('added_on', models.DateField(auto_now_add=True)),
                ('due', models.DateField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.category', verbose_name='Job Category')),
            ],
        ),
    ]
