# Generated by Django 4.0.6 on 2022-07-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_options_alter_job_table_application'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'managed': True, 'verbose_name': 'Application', 'verbose_name_plural': 'Applications'},
        ),
        migrations.AlterField(
            model_name='job',
            name='due',
            field=models.DateTimeField(),
        ),
        migrations.AlterModelTable(
            name='application',
            table='',
        ),
    ]
