# Generated by Django 4.0.6 on 2022-07-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_category_options_alter_category_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='subject',
            field=models.CharField(default='yes', max_length=50),
            preserve_default=False,
        ),
    ]
